//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public Nullable<int> booktype_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> pub_id { get; set; }
        public Nullable<System.DateTime> book_pub_date { get; set; }
        public string ISBN_No { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Tbl_author Tbl_author { get; set; }
        public virtual Tbl_bookType Tbl_bookType { get; set; }
        public virtual Tbl_publisher Tbl_publisher { get; set; }
    }
}
