//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_author
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_author()
        {
            this.Tbl_book = new HashSet<Tbl_book>();
        }
    
        public int author_id { get; set; }
        public string author_name { get; set; }
        public string author_email { get; set; }
        public Nullable<int> booktype_id { get; set; }
        public Nullable<long> phone { get; set; }
        public string password { get; set; }
    
        public virtual Tbl_bookType Tbl_bookType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_book> Tbl_book { get; set; }
    }
}
